---
- name: Watch the File
  hosts: all

  sources:
    - ansible.eda.file_watch:
        path: /tmp/test.txt
        recursive: false

  rules:
    - name: EDA file_watch test
      condition: event.type == "FileModifiedEvent"
      action:
        debug:
